apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend-deployment
spec:
  selector:
    matchLabels:
      app: chatbot-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
      - name: chatbot-frontend
        image: europe-north1-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE
        ports:
        - containerPort: 80
