name: Build image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: europe-north1
  REPOSITORY: kindly-case
  IMAGE: chatbot-frontend
  API_HOST: "http://35.228.72.81"

jobs:
  build:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/61848492826/locations/global/workloadIdentityPools/prod-pool/providers/github-provider'
        service_account: 'gke-admin@kindly-case.iam.gserviceaccount.com'

    # Login to Docker repository in Google Artifact Registry using access token
    - uses: 'docker/login-action@v1'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    # Build image
    - name: Build
      run: |-
        docker build \
          -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest" \
          --build-arg REACT_APP_API_HOST=$API_HOST \
          .
    # Push image to Docker repository in Google Artifact Registry
    - name: Publish
      run: |-
        docker push -a "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"